/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.qi.visao;

import br.edu.qi.modelo.Aluno;
import java.awt.event.KeyEvent;
import javafx.scene.input.KeyCode;
import javax.swing.JOptionPane;

/**
 *
 * @author Diogenes Wilgner
 * @since 26/06/2019 - 14:43
 * @version 1.0 Beta Xis Carne
 */
public class UICadAluno extends javax.swing.JFrame {

    /**
     * Creates new form UICadAluno
     */
    public UICadAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        jlpDados = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jlSobrenome = new javax.swing.JLabel();
        jtfSobrenome = new javax.swing.JTextField();
        jlNota1 = new javax.swing.JLabel();
        jtfNota1 = new javax.swing.JTextField();
        jlNota2 = new javax.swing.JLabel();
        jtfNota2 = new javax.swing.JTextField();
        jlPeso1 = new javax.swing.JLabel();
        jtfPeso1 = new javax.swing.JTextField();
        jlPeso2 = new javax.swing.JLabel();
        jtfPeso2 = new javax.swing.JTextField();
        jlTotalAulas = new javax.swing.JLabel();
        jtfTotalAulas = new javax.swing.JTextField();
        jrbFeminino = new javax.swing.JRadioButton();
        jrbMasculino = new javax.swing.JRadioButton();
        jlSexo = new javax.swing.JLabel();
        jlResultado = new javax.swing.JLabel();
        jspResultado = new javax.swing.JScrollPane();
        jtaResultado = new javax.swing.JTextArea();
        jlNumeroDePesencas = new javax.swing.JLabel();
        jtfPresencas = new javax.swing.JTextField();
        jlpAcoes = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlpDados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNome.setText("Nome");

        jtfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNomeKeyPressed(evt);
            }
        });

        jlSobrenome.setText("Sobrenome");

        jtfSobrenome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfSobrenomeKeyPressed(evt);
            }
        });

        jlNota1.setText("Nota 1");

        jtfNota1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNota1KeyPressed(evt);
            }
        });

        jlNota2.setText("Nota 2");

        jtfNota2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNota2KeyPressed(evt);
            }
        });

        jlPeso1.setText("Peso 1");

        jtfPeso1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPeso1KeyPressed(evt);
            }
        });

        jlPeso2.setText("Peso 2");

        jtfPeso2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPeso2KeyPressed(evt);
            }
        });

        jlTotalAulas.setText("Total de Aulas");

        jtfTotalAulas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfTotalAulasKeyPressed(evt);
            }
        });

        bgSexo.add(jrbFeminino);
        jrbFeminino.setText("Feminino");
        jrbFeminino.setActionCommand("Feminino");
        jrbFeminino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrbFemininoKeyPressed(evt);
            }
        });

        bgSexo.add(jrbMasculino);
        jrbMasculino.setText("Masculino");
        jrbMasculino.setActionCommand("Masculino");
        jrbMasculino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrbMasculinoKeyPressed(evt);
            }
        });

        jlSexo.setText("Sexo");

        jlResultado.setText("Resultado");

        jtaResultado.setColumns(20);
        jtaResultado.setRows(5);
        jtaResultado.setFocusable(false);
        jspResultado.setViewportView(jtaResultado);

        jlNumeroDePesencas.setText("Numero de Presenças");

        jtfPresencas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPresencasKeyPressed(evt);
            }
        });

        jlpDados.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtfNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlSobrenome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtfSobrenome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlNota1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtfNota1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlNota2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtfNota2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlPeso1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtfPeso1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlPeso2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtfPeso2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlTotalAulas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtfTotalAulas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrbFeminino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrbMasculino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlSexo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlResultado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jspResultado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlNumeroDePesencas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtfPresencas, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpDadosLayout = new javax.swing.GroupLayout(jlpDados);
        jlpDados.setLayout(jlpDadosLayout);
        jlpDadosLayout.setHorizontalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jlTotalAulas)
                        .addComponent(jlNome, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlSobrenome, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlNota1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlNota2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlPeso1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlPeso2, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jlNumeroDePesencas))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfPresencas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTotalAulas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtfPeso2)
                        .addComponent(jtfPeso1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jtfNota2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jtfSobrenome, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jtfNome, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jtfNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jlResultado)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpDadosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpDadosLayout.createSequentialGroup()
                                .addComponent(jlSexo)
                                .addGap(18, 18, 18)
                                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jrbFeminino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jrbMasculino))
                                .addGap(109, 109, 109))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpDadosLayout.createSequentialGroup()
                                .addComponent(jspResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))))))
        );
        jlpDadosLayout.setVerticalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNome))
                        .addGap(18, 18, 18)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlSobrenome))
                        .addGap(18, 18, 18)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNota1)
                            .addComponent(jtfNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNota2)
                            .addComponent(jtfNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlPeso1)
                            .addComponent(jtfPeso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlPeso2)
                            .addComponent(jtfPeso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlTotalAulas)
                            .addComponent(jtfTotalAulas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNumeroDePesencas)
                            .addComponent(jtfPresencas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jrbFeminino)
                                    .addComponent(jlSexo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbMasculino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE))
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jlResultado)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jspResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );

        jlpAcoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });
        jbCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCadastrarKeyPressed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        jbLimpar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbLimparKeyPressed(evt);
            }
        });

        jlpAcoes.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAcoesLayout = new javax.swing.GroupLayout(jlpAcoes);
        jlpAcoes.setLayout(jlpAcoesLayout);
        jlpAcoesLayout.setHorizontalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jbCadastrar)
                .addGap(45, 45, 45)
                .addComponent(jbLimpar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlpAcoesLayout.setVerticalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpAcoesLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar)
                    .addComponent(jbLimpar))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlpAcoes)
                    .addComponent(jlpDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jlpDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlpAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void cadastrar() {
        
        Aluno aluno = new Aluno();
        
        aluno.setNome(jtfNome.getText());
        aluno.setSobrenome(jtfSobrenome.getText());
        aluno.setNota1(Double.parseDouble(jtfNota1.getText()));
        aluno.setNota2(Double.parseDouble(jtfNota2.getText()));
        aluno.setPeso1(Double.parseDouble(jtfPeso1.getText()));
        aluno.setPeso2(Double.parseDouble(jtfPeso2.getText()));
        aluno.setPresencas(Integer.parseInt(jtfPresencas.getText()));
        aluno.setTotalAulas(Integer.parseInt(jtfTotalAulas.getText()));
        aluno.setSexo(bgSexo.getSelection().getActionCommand());
        
        jtaResultado.setText("Dados:\n " + aluno.toString());
        jtfNome.grabFocus();
    }//fecha cadastrar
    
    private void limpar() { 
        jtfNome.setText("");
        jtfSobrenome.setText("");
        jtfNota1.setText("");
        jtfNota2.setText("");
        jtfPeso1.setText("");
        jtfPeso2.setText("");
        jtfPresencas.setText("");
        jtfTotalAulas.setText("");
        bgSexo.clearSelection();
        jtfNome.grabFocus();
    }//fecha limpar
    
    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        // TODO add your handling code here:
        cadastrar();
        limpar();
        jtfNome.grabFocus();
        
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        // TODO add your handling code here:
        limpar();
        jtaResultado.setText("");
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jtfNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtfSobrenome.grabFocus();
        }
    }//GEN-LAST:event_jtfNomeKeyPressed

    private void jtfSobrenomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSobrenomeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtfNota1.grabFocus();
        }
    }//GEN-LAST:event_jtfSobrenomeKeyPressed

    private void jtfNota1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNota1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtfNota2.grabFocus();
        }
    }//GEN-LAST:event_jtfNota1KeyPressed

    private void jtfNota2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNota2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtfPeso1.grabFocus();
        }
    }//GEN-LAST:event_jtfNota2KeyPressed

    private void jtfPeso1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPeso1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtfPeso2.grabFocus();
        }
    }//GEN-LAST:event_jtfPeso1KeyPressed

    private void jtfPeso2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPeso2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtfTotalAulas.grabFocus();
        }
    }//GEN-LAST:event_jtfPeso2KeyPressed

    private void jtfPresencasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPresencasKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrbFeminino.grabFocus();
        }
    }//GEN-LAST:event_jtfPresencasKeyPressed

    private void jrbFemininoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbFemininoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrbFeminino.setSelected(true);
            jbCadastrar.grabFocus();
        }
    }//GEN-LAST:event_jrbFemininoKeyPressed

    private void jrbMasculinoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbMasculinoKeyPressed
        // TODO add your handling code here:
            jrbMasculino.setSelected(true);
            jbCadastrar.grabFocus();
    }//GEN-LAST:event_jrbMasculinoKeyPressed

    private void jbLimparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbLimparKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            limpar();
            jtaResultado.setText("");
        }
    }//GEN-LAST:event_jbLimparKeyPressed

    private void jtfTotalAulasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTotalAulasKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtfPresencas.grabFocus();
        }
    }//GEN-LAST:event_jtfTotalAulasKeyPressed

    private void jbCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCadastrarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrar();
            limpar();
            jtfNome.grabFocus();
        }
    }//GEN-LAST:event_jbCadastrarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UICadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UICadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UICadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UICadAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UICadAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNota1;
    private javax.swing.JLabel jlNota2;
    private javax.swing.JLabel jlNumeroDePesencas;
    private javax.swing.JLabel jlPeso1;
    private javax.swing.JLabel jlPeso2;
    private javax.swing.JLabel jlResultado;
    private javax.swing.JLabel jlSexo;
    private javax.swing.JLabel jlSobrenome;
    private javax.swing.JLabel jlTotalAulas;
    private javax.swing.JLayeredPane jlpAcoes;
    private javax.swing.JLayeredPane jlpDados;
    private javax.swing.JRadioButton jrbFeminino;
    private javax.swing.JRadioButton jrbMasculino;
    private javax.swing.JScrollPane jspResultado;
    private javax.swing.JTextArea jtaResultado;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfNota1;
    private javax.swing.JTextField jtfNota2;
    private javax.swing.JTextField jtfPeso1;
    private javax.swing.JTextField jtfPeso2;
    private javax.swing.JTextField jtfPresencas;
    private javax.swing.JTextField jtfSobrenome;
    private javax.swing.JTextField jtfTotalAulas;
    // End of variables declaration//GEN-END:variables
}
