/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.qi.visao;

import br.edu.qi.modelo.Cliente;
import br.edu.qi.servicos.ClienteServicos;
import br.edu.qi.servicos.ServicosFactory;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Diogenes Wilgner
 * @version 1.0
 * @since 06/07/2019 - 16:28
 */
public class UICadCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form UICadCliente
     */
    public UICadCliente() {
        initComponents();
        limpar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbgTipoDePagamento = new javax.swing.ButtonGroup();
        jlpDados = new javax.swing.JLayeredPane();
        jlCPF = new javax.swing.JLabel();
        jlCidade = new javax.swing.JLabel();
        jlEstado = new javax.swing.JLabel();
        jlNumero = new javax.swing.JLabel();
        jlRua = new javax.swing.JLabel();
        jlTipoDePagamento = new javax.swing.JLabel();
        jlNome = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jtfCPF = new javax.swing.JTextField();
        jtfCidade = new javax.swing.JTextField();
        jtfEstado = new javax.swing.JTextField();
        jtfNumero = new javax.swing.JTextField();
        jtfRua = new javax.swing.JTextField();
        jrbDinheiro = new javax.swing.JRadioButton();
        jrbDebito = new javax.swing.JRadioButton();
        jrbCredito = new javax.swing.JRadioButton();
        jrbBitcoin = new javax.swing.JRadioButton();
        jlNomeErro = new javax.swing.JLabel();
        jlCPFErro = new javax.swing.JLabel();
        jlCidadeErro = new javax.swing.JLabel();
        jlEstadoErro = new javax.swing.JLabel();
        jlNumeroErro = new javax.swing.JLabel();
        jlRuaErro = new javax.swing.JLabel();
        jlPagamentoErro = new javax.swing.JLabel();
        jlpAcoes = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jlpDados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlCPF.setText("CPF");

        jlCidade.setText("Cidade");

        jlEstado.setText("Estado");

        jlNumero.setText("Numero");

        jlRua.setText("Rua");

        jlTipoDePagamento.setText("Tipo de Pagamento");

        jlNome.setText("Nome");

        jtfNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfNomeFocusLost(evt);
            }
        });
        jtfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNomeKeyPressed(evt);
            }
        });

        jtfCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCPFFocusLost(evt);
            }
        });
        jtfCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCPFKeyPressed(evt);
            }
        });

        jtfCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCidadeFocusLost(evt);
            }
        });
        jtfCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCidadeKeyPressed(evt);
            }
        });

        jtfEstado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfEstadoFocusLost(evt);
            }
        });
        jtfEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfEstadoKeyPressed(evt);
            }
        });

        jtfNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfNumeroFocusLost(evt);
            }
        });
        jtfNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNumeroKeyPressed(evt);
            }
        });

        jtfRua.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfRuaFocusLost(evt);
            }
        });
        jtfRua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfRuaKeyPressed(evt);
            }
        });

        jbgTipoDePagamento.add(jrbDinheiro);
        jrbDinheiro.setText("Dinheiro");
        jrbDinheiro.setActionCommand("Dinheiro");
        jrbDinheiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrbDinheiroKeyPressed(evt);
            }
        });

        jbgTipoDePagamento.add(jrbDebito);
        jrbDebito.setText("Débito");
        jrbDebito.setActionCommand("Débito");
        jrbDebito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrbDebitoKeyPressed(evt);
            }
        });

        jbgTipoDePagamento.add(jrbCredito);
        jrbCredito.setText("Crédito");
        jrbCredito.setActionCommand("Crédito");
        jrbCredito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrbCreditoKeyPressed(evt);
            }
        });

        jbgTipoDePagamento.add(jrbBitcoin);
        jrbBitcoin.setText("Bitcoin");
        jrbBitcoin.setActionCommand("Bitcoin");
        jrbBitcoin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jrbBitcoinFocusLost(evt);
            }
        });
        jrbBitcoin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrbBitcoinKeyPressed(evt);
            }
        });

        jlNomeErro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/qi/imagens/accept.png"))); // NOI18N
        jlNomeErro.setText("Digite um nome!");

        jlCPFErro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/qi/imagens/accept.png"))); // NOI18N
        jlCPFErro.setText("Digite um cpf!");

        jlCidadeErro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/qi/imagens/accept.png"))); // NOI18N
        jlCidadeErro.setText("Digite uma cidade!");

        jlEstadoErro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/qi/imagens/accept.png"))); // NOI18N
        jlEstadoErro.setText("Digite um estado!");

        jlNumeroErro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/qi/imagens/accept.png"))); // NOI18N
        jlNumeroErro.setText("Digite um numero!");

        jlRuaErro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/qi/imagens/accept.png"))); // NOI18N
        jlRuaErro.setText("Digite uma rua!");

        jlPagamentoErro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/qi/imagens/accept.png"))); // NOI18N
        jlPagamentoErro.setText("Escolha uma forma de pagamento!");

        jlpDados.setLayer(jlCPF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlCidade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlEstado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlNumero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlRua, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlTipoDePagamento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtfNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtfCPF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtfCidade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtfEstado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtfNumero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtfRua, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrbDinheiro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrbDebito, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrbCredito, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrbBitcoin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlNomeErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlCPFErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlCidadeErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlEstadoErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlNumeroErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlRuaErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlPagamentoErro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpDadosLayout = new javax.swing.GroupLayout(jlpDados);
        jlpDados.setLayout(jlpDadosLayout);
        jlpDadosLayout.setHorizontalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpDadosLayout.createSequentialGroup()
                                .addComponent(jlNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpDadosLayout.createSequentialGroup()
                                .addComponent(jlCPF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpDadosLayout.createSequentialGroup()
                                .addComponent(jlCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpDadosLayout.createSequentialGroup()
                                .addComponent(jlEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpDadosLayout.createSequentialGroup()
                                .addComponent(jlNumero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addComponent(jlRua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfRua, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNomeErro)
                            .addComponent(jlCPFErro)
                            .addComponent(jlCidadeErro)
                            .addComponent(jlEstadoErro)
                            .addComponent(jlNumeroErro)
                            .addComponent(jlRuaErro))
                        .addGap(221, 221, 221))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addComponent(jlTipoDePagamento)
                        .addGap(18, 18, 18)
                        .addComponent(jrbDinheiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbDebito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbCredito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbBitcoin)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpDadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlPagamentoErro)
                .addGap(105, 105, 105))
        );
        jlpDadosLayout.setVerticalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNomeErro))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCPF)
                    .addComponent(jtfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCPFErro))
                .addGap(25, 25, 25)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCidade)
                    .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCidadeErro))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEstado)
                    .addComponent(jtfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlEstadoErro))
                .addGap(22, 22, 22)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNumero)
                    .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNumeroErro))
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlRua)
                            .addComponent(jtfRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpDadosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlRuaErro)
                        .addGap(18, 18, 18)))
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTipoDePagamento)
                    .addComponent(jrbDinheiro)
                    .addComponent(jrbDebito)
                    .addComponent(jrbCredito)
                    .addComponent(jrbBitcoin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlPagamentoErro)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jlpAcoes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });
        jbCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCadastrarKeyPressed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        jbLimpar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbLimparKeyPressed(evt);
            }
        });

        jlpAcoes.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAcoesLayout = new javax.swing.GroupLayout(jlpAcoes);
        jlpAcoes.setLayout(jlpAcoesLayout);
        jlpAcoesLayout.setHorizontalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jbCadastrar)
                .addGap(18, 18, 18)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlpAcoesLayout.setVerticalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpAcoesLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar)
                    .addComponent(jbLimpar))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpDados)
                .addContainerGap())
            .addComponent(jlpAcoes)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlpDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlpAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpar() {
        jtfCPF.setText("");
        jtfCidade.setText("");
        jtfEstado.setText("");
        jtfNome.setText("");
        jtfNumero.setText("");
        jtfRua.setText("");
        jtfNome.grabFocus();
        jbgTipoDePagamento.clearSelection();

        jlCPFErro.setVisible(false);
        jlCPFErro.setText("");
        jlNomeErro.setVisible(false);
        jlNomeErro.setText("");
        jlNumeroErro.setVisible(false);
        jlNumeroErro.setText("");
        jlCidadeErro.setVisible(false);
        jlCidadeErro.setText("");
        jlEstadoErro.setVisible(false);
        jlEstadoErro.setText("");
        jlRuaErro.setVisible(false);
        jlRuaErro.setText("");
        jlPagamentoErro.setVisible(false);
        jlPagamentoErro.setText("");

        jtfCPF.setBorder(
                BorderFactory.createLineBorder(
                        Color.lightGray));
        jtfNome.setBorder(
                BorderFactory.createLineBorder(
                        Color.lightGray));
        jtfNumero.setBorder(
                BorderFactory.createLineBorder(
                        Color.lightGray));
        jtfCidade.setBorder(
                BorderFactory.createLineBorder(
                        Color.lightGray));
        jtfEstado.setBorder(
                BorderFactory.createLineBorder(
                        Color.lightGray));
        jtfRua.setBorder(
                BorderFactory.createLineBorder(
                        Color.lightGray));
    }

    private void cadastrar() {
        try {
            //cenário Real!
            if (jtfNome.getText().isEmpty()) {
                throw new NumberFormatException("Nome inválido!");
            }

            if (jtfCPF.getText().isEmpty()) {
                throw new NumberFormatException("CPF Invalido");
            }

            if (jtfCidade.getText().isEmpty()) {
                throw new NumberFormatException("Cidade Invalida\n");
            }

            if (jtfEstado.getText().isEmpty()) {
                throw new NumberFormatException("Estado Invalido\n");
            }

            if (jtfNumero.getText().isEmpty()) {
                throw new NumberFormatException("Número Invalido\n");
            }

            if (jtfRua.getText().isEmpty()) {
                throw new NumberFormatException("Rua Invalida\n");
            }

            if (jbgTipoDePagamento.getSelection() == null) {
                throw new NumberFormatException("Escolha um método de pagamento!\n");
            }
            
            //dados cliente
            Cliente cliente = new Cliente();
            cliente.setCPF(jtfCPF.getText());
            cliente.setCidade(jtfCidade.getText());
            cliente.setEstado(jtfEstado.getText());
            cliente.setNome(jtfNome.getText());
            cliente.setNumero(Integer.parseInt(jtfNumero.getText()));
            cliente.setRua(jtfRua.getText());
            cliente.setTipoDePagamento(jbgTipoDePagamento.getSelection().getActionCommand());

            ClienteServicos clienteServicos = ServicosFactory.getClienteServicos();
            clienteServicos.cadastrarCliente(cliente);
            JOptionPane.showMessageDialog(rootPane, "Sucesso!\n Cliente cadastrado!");

        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro, dado inválido! " + numberFormatException.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);

        } catch (ArithmeticException arithmeticException) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro aritmético! " + arithmeticException.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);

        } catch (Exception exception) {
            JOptionPane.showMessageDialog(
                    this,
                    "Algum erro ocorreu! " + exception.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);

        } finally {
            System.out.println("passou em finally c:");
        }
    }//fecha cadastrar

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();
        limpar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jtfNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNomeFocusLost
        if (jtfNome.getText().isEmpty()) {
            jtfNome.setBorder(
                    BorderFactory.createLineBorder(
                            Color.red));
            //label
            jlNomeErro.setVisible(true);
            jlNomeErro.setText("Nome em branco!");

            jlNomeErro.setIcon(
                    new ImageIcon(
                            getClass().getResource(
                                    "/br/edu/qi/imagens/cancel.png")));
        } else {
            BorderFactory.createLineBorder(
                    Color.lightGray);
            jtfNome.setBorder(
                    BorderFactory.createLineBorder(
                            Color.green));
            //label
            jlNomeErro.setVisible(true);
            jlNomeErro.setText("");
            jlNomeErro.setIcon(
                    new ImageIcon(
                            getClass().getResource(
                                    "/br/edu/qi/imagens/accept.png")));
        }//fecha else

    }//GEN-LAST:event_jtfNomeFocusLost


    private void jtfCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCPFFocusLost
        if (jtfCPF.getText().isEmpty()) {
            jtfCPF.setBorder(
                    BorderFactory.createLineBorder(
                            Color.red));
            //label
            jlCPFErro.setVisible(true);
            jlCPFErro.setText("Nome em branco!");

            jlCPFErro.setIcon(
                    new ImageIcon(
                            getClass().getResource(
                                    "/br/edu/qi/imagens/cancel.png")));
        } else {
            BorderFactory.createLineBorder(
                    Color.lightGray);
            jtfCPF.setBorder(
                    BorderFactory.createLineBorder(
                            Color.green));
            //label
            jlCPFErro.setVisible(true);
            jlCPFErro.setText("");
            jlCPFErro.setIcon(
                    new ImageIcon(
                            getClass().getResource(
                                    "/br/edu/qi/imagens/accept.png")));
        }//fecha else
    }//GEN-LAST:event_jtfCPFFocusLost

    private void jtfCidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCidadeFocusLost
        if (jtfCidade.getText().isEmpty()) {
            jtfCidade.setBorder(
                    BorderFactory.createLineBorder(
                            Color.red));
            //label
            jlCidadeErro.setVisible(true);
            jlCidadeErro.setText("Nome em branco!");

            jlCidadeErro.setIcon(
                    new ImageIcon(
                            getClass().getResource(
                                    "/br/edu/qi/imagens/cancel.png")));
        } else {
            BorderFactory.createLineBorder(
                    Color.lightGray);
            jtfCidade.setBorder(
                    BorderFactory.createLineBorder(
                            Color.green));
            //label
            jlCidadeErro.setVisible(true);
            jlCidadeErro.setText("");
            jlCidadeErro.setIcon(
                    new ImageIcon(
                            getClass().getResource(
                                    "/br/edu/qi/imagens/accept.png")));
        }//fecha else
    }//GEN-LAST:event_jtfCidadeFocusLost

    private void jtfEstadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfEstadoFocusLost
        if (jtfEstado.getText().isEmpty()) {
            jtfEstado.setBorder(
                    BorderFactory.createLineBorder(
                            Color.red));
            //label
            jlEstadoErro.setVisible(true);
            jlEstadoErro.setText("Nome em branco!");

            jlEstadoErro.setIcon(
                    new ImageIcon(
                            getClass().getResource(
                                    "/br/edu/qi/imagens/cancel.png")));
        } else {
            BorderFactory.createLineBorder(
                    Color.lightGray);
            jtfEstado.setBorder(
                    BorderFactory.createLineBorder(
                            Color.green));
            //label
            jlEstadoErro.setVisible(true);
            jlEstadoErro.setText("");
            jlEstadoErro.setIcon(
                    new ImageIcon(
                            getClass().getResource(
                                    "/br/edu/qi/imagens/accept.png")));
        }//fecha else
    }//GEN-LAST:event_jtfEstadoFocusLost

    private void jtfNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNumeroFocusLost
        if (jtfNumero.getText().isEmpty()) {
            jtfNumero.setBorder(
                    BorderFactory.createLineBorder(
                            Color.red));
            //label
            jlNumeroErro.setVisible(true);
            jlNumeroErro.setText("Nome em branco!");

            jlNumeroErro.setIcon(
                    new ImageIcon(
                            getClass().getResource(
                                    "/br/edu/qi/imagens/cancel.png")));
        } else {
            BorderFactory.createLineBorder(
                    Color.lightGray);
            jtfNumero.setBorder(
                    BorderFactory.createLineBorder(
                            Color.green));
            //label
            jlNumeroErro.setVisible(true);
            jlNumeroErro.setText("");
            jlNumeroErro.setIcon(
                    new ImageIcon(
                            getClass().getResource(
                                    "/br/edu/qi/imagens/accept.png")));
        }//fecha else
    }//GEN-LAST:event_jtfNumeroFocusLost

    private void jtfRuaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfRuaFocusLost
        if (jtfRua.getText().isEmpty()) {
            jtfRua.setBorder(
                    BorderFactory.createLineBorder(
                            Color.red));
            //label
            jlRuaErro.setVisible(true);
            jlRuaErro.setText("Nome em branco!");

            jlRuaErro.setIcon(
                    new ImageIcon(
                            getClass().getResource(
                                    "/br/edu/qi/imagens/cancel.png")));
        } else {
            BorderFactory.createLineBorder(
                    Color.lightGray);
            jtfRua.setBorder(
                    BorderFactory.createLineBorder(
                            Color.green));
            //label
            jlRuaErro.setVisible(true);
            jlRuaErro.setText("");
            jlRuaErro.setIcon(
                    new ImageIcon(
                            getClass().getResource(
                                    "/br/edu/qi/imagens/accept.png")));
        }//fecha else
    }//GEN-LAST:event_jtfRuaFocusLost

    private void jrbBitcoinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jrbBitcoinFocusLost
        if (jbgTipoDePagamento.getSelection() == null) {
            jlPagamentoErro.setText("Escolha um sexo");
            jlPagamentoErro.setVisible(true);
            jlPagamentoErro.setIcon(
                    new ImageIcon(
                            getClass().getResource(
                                    "/br/edu/qi/imagens/cancel.png")));
        } else {
            jlPagamentoErro.setText("");
            jlPagamentoErro.setVisible(false);
            jlPagamentoErro.setIcon(
                    new ImageIcon(
                            getClass().getResource(
                                    "/br/edu/qi/imagens/accept.png")));
        }
    }//GEN-LAST:event_jrbBitcoinFocusLost

    private void jtfNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtfCPF.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtfNomeKeyPressed

    private void jtfCPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCPFKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtfCidade.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtfCPFKeyPressed

    private void jtfCidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCidadeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtfEstado.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtfCidadeKeyPressed

    private void jtfEstadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfEstadoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtfNumero.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtfEstadoKeyPressed

    private void jtfNumeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNumeroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtfRua.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtfNumeroKeyPressed

    private void jtfRuaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfRuaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrbDinheiro.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtfRuaKeyPressed

    private void jrbDinheiroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbDinheiroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrbDinheiro.setSelected(true);
            jbCadastrar.grabFocus();

        }//fecha if
    }//GEN-LAST:event_jrbDinheiroKeyPressed

    private void jrbDebitoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbDebitoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrbDebito.setSelected(true);
            jbCadastrar.grabFocus();

        }//fecha if
    }//GEN-LAST:event_jrbDebitoKeyPressed

    private void jrbCreditoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbCreditoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrbCredito.setSelected(true);
            jbCadastrar.grabFocus();

        }//fecha if
    }//GEN-LAST:event_jrbCreditoKeyPressed

    private void jrbBitcoinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbBitcoinKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrbBitcoin.setSelected(true);
            jbCadastrar.grabFocus();

        }//fecha if
    }//GEN-LAST:event_jrbBitcoinKeyPressed

    private void jbCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCadastrarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrar();
            jbLimpar.grabFocus();

        }//fecha if
    }//GEN-LAST:event_jbCadastrarKeyPressed

    private void jbLimparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbLimparKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            limpar();
            jtfNome.grabFocus();

        }//fecha if
    }//GEN-LAST:event_jbLimparKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.ButtonGroup jbgTipoDePagamento;
    private javax.swing.JLabel jlCPF;
    private javax.swing.JLabel jlCPFErro;
    private javax.swing.JLabel jlCidade;
    private javax.swing.JLabel jlCidadeErro;
    private javax.swing.JLabel jlEstado;
    private javax.swing.JLabel jlEstadoErro;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNomeErro;
    private javax.swing.JLabel jlNumero;
    private javax.swing.JLabel jlNumeroErro;
    private javax.swing.JLabel jlPagamentoErro;
    private javax.swing.JLabel jlRua;
    private javax.swing.JLabel jlRuaErro;
    private javax.swing.JLabel jlTipoDePagamento;
    private javax.swing.JLayeredPane jlpAcoes;
    private javax.swing.JLayeredPane jlpDados;
    private javax.swing.JRadioButton jrbBitcoin;
    private javax.swing.JRadioButton jrbCredito;
    private javax.swing.JRadioButton jrbDebito;
    private javax.swing.JRadioButton jrbDinheiro;
    private javax.swing.JTextField jtfCPF;
    private javax.swing.JTextField jtfCidade;
    private javax.swing.JTextField jtfEstado;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfNumero;
    private javax.swing.JTextField jtfRua;
    // End of variables declaration//GEN-END:variables
}
