CREATE DATABASE locadora;
USE locadora;
CREATE TABLE cliente(
CPF CHAR(14) PRIMARY KEY NOT NULL,
nome VARCHAR(50) NOT NULL,
idade SMALLINT NOT NULL,
logradouro VARCHAR(50) NOT NULL,
numero INT NOT NULL,
bairro VARCHAR(30) NOT NULL,
cidade VARCHAR(40) NOT NULL,
CEP CHAR(9) NOT NULL,
UF VARCHAR(25) NOT NULL,
cartaCredito CHAR(16) NOT NULL,
dataCadastro DATE NOT NULL
);

CREATE TABLE funcionario(
CPF CHAR(14) PRIMARY KEY NOT NULL,
nome VARCHAR(50) NOT NULL,
idade SMALLINT NOT NULL,
logradouro VARCHAR(50) NOT NULL,
numero INT NOT NULL,
bairro VARCHAR(30) NOT NULL,
cidade VARCHAR(40) NOT NULL,
CEP CHAR(9) NOT NULL,
UF VARCHAR(25) NOT NULL,
quantidadeHora INT NOT NULL,
valorHora DOUBLE NOT NULL
);

CREATE TABLE passeio(
placa CHAR(7) PRIMARY KEY NOT NULL,
modelo VARCHAR(30) NOT NULL,
marca VARCHAR(30) NOT NULL,
renavam CHAR(11) NOT NULL,
chassi CHAR(17) NOT NULL,
carro ENUM ('Sim','Não') NOT NULL, 
moto ENUM ('Sim','Não') NOT NULL
);

CREATE TABLE utilitario(
placa CHAR(7) PRIMARY KEY NOT NULL,
modelo VARCHAR(30) NOT NULL,
marca VARCHAR(30) NOT NULL,
renavam CHAR(11) NOT NULL,
chassi CHAR(17) NOT NULL,
esportivo ENUM ('Sim','Não') NOT NULL, 
tradicional ENUM ('Sim','Não') NOT NULL
);
