// *****************************************************************************
// * This is an automatically generated header file for UI Element definition  *
// * resource symbols and values. Please do not modify manually.               *
// *****************************************************************************

#pragma once

#define cmdTabOpcoes 2 
#define cmdTabOpcoes_LabelTitle_RESID 60001
#define cmdTabConceitual 3 
#define cmdTabConceitual_LabelTitle_RESID 60002
#define cmdTabLogico 4 
#define cmdTabLogico_LabelTitle_RESID 60003
#define cmdTabConfiguracao 5 
#define cmdTabConfiguracao_LabelTitle_RESID 60004
#define cmdGroupOpcoes 6 
#define cmdGroupOpcoes_LabelTitle_RESID 60005
#define cmdGroupFerramentasConceitual 7 
#define cmdGroupFerramentasConceitual_LabelTitle_RESID 60006
#define cmdGroupFerramentasLogico 8 
#define cmdGroupFerramentasLogico_LabelTitle_RESID 60007
#define cmdGroupComandosConceitual 9 
#define cmdGroupComandosConceitual_LabelTitle_RESID 60008
#define cmdGroupComandosLogico 10 
#define cmdGroupComandosLogico_LabelTitle_RESID 60009
#define cmdNovoConceitual 11 
#define cmdNovoConceitual_LabelTitle_RESID 60010
#define cmdNovoConceitual_LabelDescription_RESID 60011
#define cmdNovoConceitual_TooltipTitle_RESID 60012
#define cmdNovoConceitual_TooltipDescription_RESID 60013
#define cmdNovoConceitual_SmallImages_RESID 60014
#define cmdNovoConceitual_LargeImages_RESID 60015
#define cmdCriarEntidade 12 
#define cmdCriarEntidade_LabelTitle_RESID 60016
#define cmdCriarEntidade_TooltipTitle_RESID 60017
#define cmdCriarEntidade_TooltipDescription_RESID 60018
#define cmdCriarEntidade_SmallImages_RESID 60019
#define cmdCriarEntidade_LargeImages_RESID 60020
#define cmdCriarAtributo 13 
#define cmdCriarAtributo_LabelTitle_RESID 60021
#define cmdCriarAtributo_TooltipTitle_RESID 60022
#define cmdCriarAtributo_TooltipDescription_RESID 60023
#define cmdCriarAtributo_SmallImages_RESID 60024
#define cmdCriarAtributo_LargeImages_RESID 60025
#define cmdCriarAtributoIdentificador 14 
#define cmdCriarAtributoIdentificador_LabelTitle_RESID 60026
#define cmdCriarAtributoIdentificador_TooltipTitle_RESID 60027
#define cmdCriarAtributoIdentificador_TooltipDescription_RESID 60028
#define cmdCriarAtributoIdentificador_SmallImages_RESID 60029
#define cmdCriarAtributoIdentificador_LargeImages_RESID 60030
#define cmdCriarAtributoComposto 15 
#define cmdCriarAtributoComposto_LabelTitle_RESID 60031
#define cmdCriarAtributoComposto_TooltipTitle_RESID 60032
#define cmdCriarAtributoComposto_TooltipDescription_RESID 60033
#define cmdCriarAtributoComposto_SmallImages_RESID 60034
#define cmdCriarAtributoComposto_LargeImages_RESID 60035
#define cmdCriarAtributoMultivalorado 16 
#define cmdCriarAtributoMultivalorado_LabelTitle_RESID 60036
#define cmdCriarAtributoMultivalorado_TooltipTitle_RESID 60037
#define cmdCriarAtributoMultivalorado_TooltipDescription_RESID 60038
#define cmdCriarAtributoMultivalorado_SmallImages_RESID 60039
#define cmdCriarAtributoMultivalorado_LargeImages_RESID 60040
#define cmdCriarAtributoOpcional 17 
#define cmdCriarAtributoOpcional_LabelTitle_RESID 60041
#define cmdCriarAtributoOpcional_TooltipTitle_RESID 60042
#define cmdCriarAtributoOpcional_TooltipDescription_RESID 60043
#define cmdCriarAtributoOpcional_SmallImages_RESID 60044
#define cmdCriarAtributoOpcional_LargeImages_RESID 60045
#define cmdCriarRelacao 18 
#define cmdCriarRelacao_LabelTitle_RESID 60046
#define cmdCriarRelacao_TooltipTitle_RESID 60047
#define cmdCriarRelacao_TooltipDescription_RESID 60048
#define cmdCriarRelacao_SmallImages_RESID 60049
#define cmdCriarRelacao_LargeImages_RESID 60050
#define cmdCriarEntidadeAssociativa 19 
#define cmdCriarEntidadeAssociativa_LabelTitle_RESID 60051
#define cmdCriarEntidadeAssociativa_TooltipTitle_RESID 60052
#define cmdCriarEntidadeAssociativa_TooltipDescription_RESID 60053
#define cmdCriarEntidadeAssociativa_SmallImages_RESID 60054
#define cmdCriarEntidadeAssociativa_LargeImages_RESID 60055
#define cmdCriarEspecializacao 20 
#define cmdCriarEspecializacao_LabelTitle_RESID 60056
#define cmdCriarEspecializacao_TooltipTitle_RESID 60057
#define cmdCriarEspecializacao_TooltipDescription_RESID 60058
#define cmdCriarEspecializacao_SmallImages_RESID 60059
#define cmdCriarEspecializacao_LargeImages_RESID 60060
#define cmdCriarEspecializacaoExcEntidade 21 
#define cmdCriarEspecializacaoExcEntidade_LabelTitle_RESID 60061
#define cmdCriarEspecializacaoExcEntidade_TooltipTitle_RESID 60062
#define cmdCriarEspecializacaoExcEntidade_TooltipDescription_RESID 60063
#define cmdCriarEspecializacaoExcEntidade_SmallImages_RESID 60064
#define cmdCriarEspecializacaoExcEntidade_LargeImages_RESID 60065
#define cmdCriarEspecializacaoNaoExcEntidade 22 
#define cmdCriarEspecializacaoNaoExcEntidade_LabelTitle_RESID 60066
#define cmdCriarEspecializacaoNaoExcEntidade_TooltipTitle_RESID 60067
#define cmdCriarEspecializacaoNaoExcEntidade_TooltipDescription_RESID 60068
#define cmdCriarEspecializacaoNaoExcEntidade_SmallImages_RESID 60069
#define cmdCriarEspecializacaoNaoExcEntidade_LargeImages_RESID 60070
#define cmdAutoRelacionar 23 
#define cmdAutoRelacionar_LabelTitle_RESID 60071
#define cmdAutoRelacionar_TooltipTitle_RESID 60072
#define cmdAutoRelacionar_TooltipDescription_RESID 60073
#define cmdAutoRelacionar_SmallImages_RESID 60074
#define cmdAutoRelacionar_LargeImages_RESID 60075
#define cmdLigarObjetos 24 
#define cmdLigarObjetos_LabelTitle_RESID 60076
#define cmdLigarObjetos_TooltipTitle_RESID 60077
#define cmdLigarObjetos_TooltipDescription_RESID 60078
#define cmdLigarObjetos_SmallImages_RESID 60079
#define cmdLigarObjetos_LargeImages_RESID 60080
#define cmdCriarObservacao 25 
#define cmdCriarObservacao_LabelTitle_RESID 60081
#define cmdCriarObservacao_TooltipTitle_RESID 60082
#define cmdCriarObservacao_TooltipDescription_RESID 60083
#define cmdCriarObservacao_SmallImages_RESID 60084
#define cmdCriarObservacao_LargeImages_RESID 60085
#define cmdApagarConceitual 26 
#define cmdApagarConceitual_LabelTitle_RESID 60086
#define cmdApagarConceitual_TooltipTitle_RESID 60087
#define cmdApagarConceitual_TooltipDescription_RESID 60088
#define cmdExcluirSelecionadoConceitual 27 
#define cmdExcluirSelecionadoConceitual_LabelTitle_RESID 60089
#define cmdExcluirSelecionadoConceitual_TooltipTitle_RESID 60090
#define cmdExcluirSelecionadoConceitual_TooltipDescription_RESID 60091
#define cmdExcluirSelecionadoConceitual_SmallImages_RESID 60092
#define cmdExcluirSelecionadoConceitual_LargeImages_RESID 60093
#define cmdNovoLogico 28 
#define cmdNovoLogico_LabelTitle_RESID 60094
#define cmdNovoLogico_LabelDescription_RESID 60095
#define cmdNovoLogico_TooltipTitle_RESID 60096
#define cmdNovoLogico_TooltipDescription_RESID 60097
#define cmdNovoLogico_SmallImages_RESID 60098
#define cmdNovoLogico_LargeImages_RESID 60099
#define cmdAbrir 29 
#define cmdAbrir_LabelTitle_RESID 60100
#define cmdAbrir_SmallImages_RESID 60101
#define cmdAbrir_LargeImages_RESID 60102
#define cmdSalvar 30 
#define cmdSalvar_LabelTitle_RESID 60103
#define cmdSalvar_SmallImages_RESID 60104
#define cmdSalvar_LargeImages_RESID 60105
#define cmdSalvarComo 31 
#define cmdSalvarComo_LabelTitle_RESID 60106
#define cmdSalvarComo_SmallImages_RESID 60107
#define cmdSalvarComo_LargeImages_RESID 60108
#define cmdFechar 32 
#define cmdFechar_LabelTitle_RESID 60109
#define cmdFechar_SmallImages_RESID 60110
#define cmdFechar_LargeImages_RESID 60111
#define cmdExportarJPEG 33 
#define cmdExportarJPEG_LabelTitle_RESID 60112
#define cmdExportarJPEG_LabelDescription_RESID 60113
#define cmdExportarJPEG_SmallImages_RESID 60114
#define cmdExportarJPEG_LargeImages_RESID 60115
#define cmdExportarBMP 34 
#define cmdExportarBMP_LabelTitle_RESID 60116
#define cmdExportarBMP_LabelDescription_RESID 60117
#define cmdExportarBMP_SmallImages_RESID 60118
#define cmdExportarBMP_LargeImages_RESID 60119
#define cmdImprimir 35 
#define cmdImprimir_LabelTitle_RESID 60120
#define cmdImprimir_LabelDescription_RESID 60121
#define cmdImprimir_SmallImages_RESID 60122
#define cmdImprimir_LargeImages_RESID 60123
#define cmdGerarDicionario 36 
#define cmdGerarDicionario_LabelTitle_RESID 60124
#define cmdGerarDicionario_LabelDescription_RESID 60125
#define cmdGerarDicionario_SmallImages_RESID 60126
#define cmdGerarDicionario_LargeImages_RESID 60127
#define cmdAjuda 37 
#define cmdAjuda_LabelTitle_RESID 60128
#define cmdConfiguracoes 38 
#define cmdConfiguracoes_LabelTitle_RESID 60129
#define cmdConfiguracoes_SmallImages_RESID 60130
#define cmdConfiguracoes_LargeImages_RESID 60131
#define cmdCancelarConceitual 39 
#define cmdCancelarConceitual_LabelTitle_RESID 60132
#define cmdCancelarConceitual_SmallImages_RESID 60133
#define cmdCancelarConceitual_LargeImages_RESID 60134
#define cmdCancelarLogico 40 
#define cmdCancelarLogico_LabelTitle_RESID 60135
#define cmdCancelarLogico_SmallImages_RESID 60136
#define cmdCancelarLogico_LargeImages_RESID 60137
#define cmdAutoSalvar 41 
#define cmdAutoSalvar_LabelTitle_RESID 60138
#define cmdAutoSalvar_SmallImages_RESID 60139
#define cmdAutoSalvar_LargeImages_RESID 60140
#define cmdSair 42 
#define cmdSair_LabelTitle_RESID 60141
#define cmdSair_SmallImages_RESID 60142
#define cmdSair_LargeImages_RESID 60143
#define cmdSobre 43 
#define cmdSobre_LabelTitle_RESID 60144
#define cmdSobre_SmallImages_RESID 60145
#define cmdSobre_LargeImages_RESID 60146
#define cmdSiteBrModelo 44 
#define cmdSiteBrModelo_LabelTitle_RESID 60147
#define cmdSiteBrModelo_SmallImages_RESID 60148
#define cmdSiteBrModelo_LargeImages_RESID 60149
#define cmdAtributoMais 45 
#define cmdAtributoMais_LabelTitle_RESID 60150
#define cmdAtributoMais_SmallImages_RESID 60151
#define cmdAtributoMais_LargeImages_RESID 60152
#define cmdEspecializacaoMais 46 
#define cmdEspecializacaoMais_LabelTitle_RESID 60153
#define cmdEspecializacaoMais_SmallImages_RESID 60154
#define cmdEspecializacaoMais_LargeImages_RESID 60155
#define cmdEntidadeMais 47 
#define cmdEntidadeMais_LabelTitle_RESID 60156
#define cmdEntidadeMais_SmallImages_RESID 60157
#define cmdEntidadeMais_LargeImages_RESID 60158
#define cmdDesfazer 48 
#define cmdDesfazer_LabelTitle_RESID 60159
#define cmdDesfazer_TooltipDescription_RESID 60160
#define cmdDesfazer_SmallImages_RESID 60161
#define cmdDesfazer_LargeImages_RESID 60162
#define cmdRefazer 49 
#define cmdRefazer_LabelTitle_RESID 60163
#define cmdRefazer_TooltipDescription_RESID 60164
#define cmdRefazer_SmallImages_RESID 60165
#define cmdRefazer_LargeImages_RESID 60166
#define cmdGroupClipboard 50 
#define cmdGroupClipboard_LabelTitle_RESID 60167
#define cmdColar 51 
#define cmdColar_LabelTitle_RESID 60168
#define cmdColar_TooltipTitle_RESID 60169
#define cmdColar_TooltipDescription_RESID 60170
#define cmdColar_SmallImages_RESID 60171
#define cmdColar_LargeImages_RESID 60172
#define cmdCopiar 52 
#define cmdCopiar_LabelTitle_RESID 60173
#define cmdCopiar_TooltipTitle_RESID 60174
#define cmdCopiar_TooltipDescription_RESID 60175
#define cmdCopiar_SmallImages_RESID 60176
#define cmdCopiar_LargeImages_RESID 60177
#define cmdRecortar 53 
#define cmdRecortar_LabelTitle_RESID 60178
#define cmdRecortar_TooltipTitle_RESID 60179
#define cmdRecortar_TooltipDescription_RESID 60180
#define cmdRecortar_SmallImages_RESID 60181
#define cmdRecortar_LargeImages_RESID 60182
#define cmdGroupEdicao 54 
#define cmdGroupEdicao_LabelTitle_RESID 60183
#define cmdCriarTabela 55 
#define cmdCriarTabela_LabelTitle_RESID 60184
#define cmdCriarTabela_TooltipTitle_RESID 60185
#define cmdCriarTabela_TooltipDescription_RESID 60186
#define cmdCriarTabela_SmallImages_RESID 60187
#define cmdCriarTabela_LargeImages_RESID 60188
#define cmdCriarCampo 56 
#define cmdCriarCampo_LabelTitle_RESID 60189
#define cmdCriarCampo_TooltipTitle_RESID 60190
#define cmdCriarCampo_TooltipDescription_RESID 60191
#define cmdCriarCampo_SmallImages_RESID 60192
#define cmdCriarCampo_LargeImages_RESID 60193
#define cmdCriarRelacionamento 57 
#define cmdCriarRelacionamento_LabelTitle_RESID 60194
#define cmdCriarRelacionamento_TooltipTitle_RESID 60195
#define cmdCriarRelacionamento_TooltipDescription_RESID 60196
#define cmdCriarRelacionamento_SmallImages_RESID 60197
#define cmdCriarRelacionamento_LargeImages_RESID 60198
#define cmdCriarChaveEstrangeira 58 
#define cmdCriarChaveEstrangeira_LabelTitle_RESID 60199
#define cmdCriarChaveEstrangeira_TooltipTitle_RESID 60200
#define cmdCriarChaveEstrangeira_TooltipDescription_RESID 60201
#define cmdCriarChaveEstrangeira_SmallImages_RESID 60202
#define cmdCriarChaveEstrangeira_LargeImages_RESID 60203
#define cmdCriarChavePrimaria 59 
#define cmdCriarChavePrimaria_LabelTitle_RESID 60204
#define cmdCriarChavePrimaria_TooltipTitle_RESID 60205
#define cmdCriarChavePrimaria_TooltipDescription_RESID 60206
#define cmdCriarChavePrimaria_SmallImages_RESID 60207
#define cmdCriarChavePrimaria_LargeImages_RESID 60208
#define cmdCriarSeparadosCampos 60 
#define cmdCriarSeparadosCampos_LabelTitle_RESID 60209
#define cmdCriarSeparadosCampos_TooltipTitle_RESID 60210
#define cmdCriarSeparadosCampos_TooltipDescription_RESID 60211
#define cmdCriarSeparadosCampos_SmallImages_RESID 60212
#define cmdCriarSeparadosCampos_LargeImages_RESID 60213
#define cmdGroupDocumentacao 61 
#define cmdGroupDocumentacao_LabelTitle_RESID 60214
#define cmdVisualizarXML 62 
#define cmdVisualizarXML_LabelTitle_RESID 60215
#define cmdVisualizarXML_TooltipTitle_RESID 60216
#define cmdVisualizarXML_TooltipDescription_RESID 60217
#define cmdVisualizarXML_SmallImages_RESID 60218
#define cmdVisualizarXML_LargeImages_RESID 60219
#define cmdExibirLog 63 
#define cmdExibirLog_LabelTitle_RESID 60220
#define cmdExibirLog_TooltipTitle_RESID 60221
#define cmdExibirLog_TooltipDescription_RESID 60222
#define cmdExibirLog_SmallImages_RESID 60223
#define cmdExibirLog_LargeImages_RESID 60224
#define cmdLimparLog 64 
#define cmdLimparLog_LabelTitle_RESID 60225
#define cmdLimparLog_TooltipTitle_RESID 60226
#define cmdLimparLog_TooltipDescription_RESID 60227
#define cmdLimparLog_SmallImages_RESID 60228
#define cmdLimparLog_LargeImages_RESID 60229
#define cmdSalvarLog 65 
#define cmdSalvarLog_LabelTitle_RESID 60230
#define cmdSalvarLog_TooltipTitle_RESID 60231
#define cmdSalvarLog_TooltipDescription_RESID 60232
#define cmdSalvarLog_SmallImages_RESID 60233
#define cmdSalvarLog_LargeImages_RESID 60234
#define cmdGroupFonte 66 
#define cmdGroupFonte_LabelTitle_RESID 60235
#define cmdSelecionarFonte 67 
#define cmdSelecionarFonte_LabelTitle_RESID 60236
#define cmdSelecionarFonte_TooltipTitle_RESID 60237
#define cmdSelecionarFonte_TooltipDescription_RESID 60238
#define cmdSelecionarFonte_SmallImages_RESID 60239
#define cmdSelecionarFonte_LargeImages_RESID 60240
#define cmdEditarTemplateConversao 68 
#define cmdEditarTemplateConversao_LabelTitle_RESID 60241
#define cmdGroupOperacoesConceitual 69 
#define cmdGroupOperacoesConceitual_LabelTitle_RESID 60242
#define cmdOcultarAtributo 70 
#define cmdOcultarAtributo_LabelTitle_RESID 60243
#define cmdOrganizarAtributos 71 
#define cmdOrganizarAtributos_LabelTitle_RESID 60244
#define cmdSelecionarAtributo 72 
#define cmdSelecionarAtributo_LabelTitle_RESID 60245
#define cmdPromoverEntidadeAssociativa 73 
#define cmdPromoverEntidadeAssociativa_LabelTitle_RESID 60246
#define cmdPromoverEntidade 74 
#define cmdPromoverEntidade_LabelTitle_RESID 60247
#define cmdConverterEspParaRestrita 75 
#define cmdConverterEspParaRestrita_LabelTitle_RESID 60248
#define cmdConverterEspParaOpcional 76 
#define cmdConverterEspParaOpcional_LabelTitle_RESID 60249
#define cmdDicionarioDadosObjConceitual 77 
#define cmdDicionarioDadosObjConceitual_LabelTitle_RESID 60250
#define cmdGerarEsquemaLogico 78 
#define cmdGerarEsquemaLogico_LabelTitle_RESID 60251
#define cmdGerarEsquemaLogico_SmallImages_RESID 60252
#define cmdGerarEsquemaLogico_LargeImages_RESID 60253
#define cmdOperacoesConceitualMais 79 
#define cmdOperacoesConceitualMais_LabelTitle_RESID 60254
#define cmdOperacoesConceitualMais_SmallImages_RESID 60255
#define cmdOperacoesConceitualMais_LargeImages_RESID 60256
#define cmdGerarEsquemaFisico 80 
#define cmdGerarEsquemaFisico_LabelTitle_RESID 60257
#define cmdGerarEsquemaFisico_SmallImages_RESID 60258
#define cmdGerarEsquemaFisico_LargeImages_RESID 60259
#define cmdGroupOperacoesLogico 81 
#define cmdGroupOperacoesLogico_LabelTitle_RESID 60260
#define cmdOperacoesLogicoMais 82 
#define cmdOperacoesLogicoMais_LabelTitle_RESID 60261
#define cmdOperacoesLogicoMais_SmallImages_RESID 60262
#define cmdOperacoesLogicoMais_LargeImages_RESID 60263
#define cmdDicionarioDadosObjLogico 83 
#define cmdDicionarioDadosObjLogico_LabelTitle_RESID 60264
#define cmdIncluirAlterarXLS 84 
#define cmdIncluirAlterarXLS_LabelTitle_RESID 60265
#define cmdModelosRecentes 85 
#define cmdModelosRecentes_LabelTitle_RESID 60266
#define cmdHeaderExportar 86 
#define cmdHeaderExportar_LabelTitle_RESID 60267
#define cmdHeaderExportar_SmallImages_RESID 60268
#define cmdHeaderExportar_LargeImages_RESID 60269
#define cmdExportarSubMenu 87 
#define cmdExportarSubMenu_LabelTitle_RESID 60270
#define cmdHeaderNovoModelo 88 
#define cmdHeaderNovoModelo_LabelTitle_RESID 60271
#define cmdHeaderNovoModelo_SmallImages_RESID 60272
#define cmdHeaderNovoModelo_LargeImages_RESID 60273
#define cmdNovoModeloSubMenu 89 
#define cmdNovoModeloSubMenu_LabelTitle_RESID 60274
#define cmdHeaderDocumentosRecentes 90 
#define cmdHeaderDocumentosRecentes_LabelTitle_RESID 60275
#define cmdHeaderImpressao 91 
#define cmdHeaderImpressao_LabelTitle_RESID 60276
#define cmdHeaderImpressao_SmallImages_RESID 60277
#define cmdHeaderImpressao_LargeImages_RESID 60278
#define cmdImpressaoSubMenu 92 
#define cmdImpressaoSubMenu_LabelTitle_RESID 60279
#define cmdImprimirMais 93 
#define cmdImprimirMais_LabelTitle_RESID 60280
#define cmdImprimirMais_SmallImages_RESID 60281
#define cmdImprimirMais_LargeImages_RESID 60282
#define cmdDocRecentes 94 
#define cmdDocRecentes_LabelTitle_RESID 60283
