/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.qi.visao;
import br.edu.qi.modelo.Motorista;
import java.awt.Color;
import javax.swing.BorderFactory;
import br.edu.qi.servicos.MotoristaServicos;
import br.edu.qi.servicos.ServicosFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author Diogenes Wilgner da Silva    
 * @version 1.0 
 * @since 10/07/2019 - 17:07
 */
public class UICadMotorista extends javax.swing.JInternalFrame {

    /**
     * Creates new form UICadMotorista
     */
    public UICadMotorista() {
        initComponents();
        limpar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbgVeiculo = new javax.swing.ButtonGroup();
        jlpDados = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jlCpf = new javax.swing.JLabel();
        jlCnh = new javax.swing.JLabel();
        jlVeiculo = new javax.swing.JLabel();
        jlPlaca = new javax.swing.JLabel();
        jlChassi = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jtfCpf = new javax.swing.JTextField();
        jtfCnh = new javax.swing.JTextField();
        jtfPlaca = new javax.swing.JTextField();
        jtfChassi = new javax.swing.JTextField();
        jrbCarro = new javax.swing.JRadioButton();
        jrbMoto = new javax.swing.JRadioButton();
        jrbBicicleta = new javax.swing.JRadioButton();
        jrbPatinete = new javax.swing.JRadioButton();
        jlNomeErro = new javax.swing.JLabel();
        jlCpfErro = new javax.swing.JLabel();
        jlCnhErro = new javax.swing.JLabel();
        jlPlacaErro = new javax.swing.JLabel();
        jlChassiErro = new javax.swing.JLabel();
        jlVeiculoErro = new javax.swing.JLabel();
        jlpAcoes = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        jlpDados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNome.setText("Nome");

        jlCpf.setText("CPF");

        jlCnh.setText("CNH");

        jlVeiculo.setText("Veiculo");

        jlPlaca.setText("Placa");

        jlChassi.setText("Chassi");

        jbgVeiculo.add(jrbCarro);
        jrbCarro.setText("Carro");
        jrbCarro.setActionCommand("Carro");

        jbgVeiculo.add(jrbMoto);
        jrbMoto.setText("Moto");
        jrbMoto.setActionCommand("Moto");

        jbgVeiculo.add(jrbBicicleta);
        jrbBicicleta.setText("Bicicleta");
        jrbBicicleta.setActionCommand("Bicicleta");

        jbgVeiculo.add(jrbPatinete);
        jrbPatinete.setText("Patinete");
        jrbPatinete.setActionCommand("Patinete");

        jlNomeErro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/qi/imagens/accept.png"))); // NOI18N
        jlNomeErro.setText("Digite um nome!");

        jlCpfErro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/qi/imagens/accept.png"))); // NOI18N
        jlCpfErro.setText("Digite um CPF!");

        jlCnhErro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/qi/imagens/accept.png"))); // NOI18N
        jlCnhErro.setText("Digite um CNH");

        jlPlacaErro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/qi/imagens/accept.png"))); // NOI18N
        jlPlacaErro.setText("Digite uma Placa!");

        jlChassiErro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/qi/imagens/accept.png"))); // NOI18N
        jlChassiErro.setText("Digite o Chassi");

        jlVeiculoErro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/qi/imagens/accept.png"))); // NOI18N
        jlVeiculoErro.setText("Selecione um veículo!");

        jlpDados.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlCpf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlCnh, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlVeiculo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlPlaca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlChassi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtfNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtfCpf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtfCnh, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtfPlaca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtfChassi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrbCarro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrbMoto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrbBicicleta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrbPatinete, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlNomeErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlCpfErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlCnhErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlPlacaErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlChassiErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlVeiculoErro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpDadosLayout = new javax.swing.GroupLayout(jlpDados);
        jlpDados.setLayout(jlpDadosLayout);
        jlpDadosLayout.setHorizontalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlNome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCpf, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlChassi, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlPlaca, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCnh, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(60, 60, 60)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtfCpf)
                        .addComponent(jtfCnh)
                        .addComponent(jtfPlaca)
                        .addComponent(jtfChassi, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNomeErro)
                    .addComponent(jlCpfErro)
                    .addComponent(jlCnhErro)
                    .addComponent(jlPlacaErro)
                    .addComponent(jlChassiErro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbBicicleta)
                            .addComponent(jrbCarro))
                        .addGap(24, 24, 24)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbMoto)
                            .addComponent(jrbPatinete)))
                    .addComponent(jlVeiculo)
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jlVeiculoErro)))
                .addGap(66, 66, 66))
        );
        jlpDadosLayout.setVerticalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addComponent(jlNome)
                        .addGap(18, 18, 18)
                        .addComponent(jlCpf)
                        .addGap(31, 31, 31)
                        .addComponent(jlCnh))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jlpDadosLayout.createSequentialGroup()
                                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlNomeErro))
                                        .addGap(18, 18, 18)
                                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlCpfErro))
                                        .addGap(18, 18, 18)
                                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jtfCnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlCnhErro)))
                                    .addGroup(jlpDadosLayout.createSequentialGroup()
                                        .addComponent(jlVeiculo)
                                        .addGap(9, 9, 9)
                                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jrbCarro)
                                            .addComponent(jrbMoto))
                                        .addGap(22, 22, 22)
                                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jrbBicicleta)
                                            .addComponent(jrbPatinete))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jtfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jlPlaca))
                                    .addComponent(jlVeiculoErro)))
                            .addComponent(jlPlacaErro))
                        .addGap(22, 22, 22)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlChassiErro)
                            .addComponent(jlChassi))))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jlpAcoes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jlpAcoes.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAcoesLayout = new javax.swing.GroupLayout(jlpAcoes);
        jlpAcoes.setLayout(jlpAcoesLayout);
        jlpAcoesLayout.setHorizontalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jlpAcoesLayout.setVerticalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlpDados)
                    .addComponent(jlpAcoes))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlpAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();
        limpar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void limpar() {

        jtfNome.grabFocus();
        jtfChassi.setText("");
        jtfCnh.setText("");
        jtfCpf.setText("");
        jtfNome.setText("");
        jtfPlaca.setText("");
        jbgVeiculo.clearSelection();

        jlChassiErro.setVisible(false);
        jlChassiErro.setText("");
        jlNomeErro.setVisible(false);
        jlNomeErro.setText("");
        jlCnhErro.setVisible(false);
        jlCnhErro.setText("");
        jlCpfErro.setVisible(false);
        jlCpfErro.setText("");
        jlPlacaErro.setVisible(false);
        jlPlacaErro.setText("");
        jlVeiculoErro.setVisible(false);
        jlVeiculoErro.setText("");

        jtfCpf.setBorder(
                BorderFactory.createLineBorder(
                        Color.lightGray));
        jtfNome.setBorder(
                BorderFactory.createLineBorder(
                        Color.lightGray));
        jtfCnh.setBorder(
                BorderFactory.createLineBorder(
                        Color.lightGray));
        jtfChassi.setBorder(
                BorderFactory.createLineBorder(
                        Color.lightGray));
        jtfPlaca.setBorder(
                BorderFactory.createLineBorder(
                        Color.lightGray));
    }//fecha limpar
    
    private void cadastrar() {
        try {
            //cenário Real!
            if (jtfNome.getText().isEmpty()) {
                throw new NumberFormatException("Nome inválido!");
            }

            if (jtfCpf.getText().isEmpty()) {
                throw new NumberFormatException("CPF Invalido");
            }

            if (jtfCnh.getText().isEmpty()) {
                throw new NumberFormatException("CNH Invalida\n");
            }

            if (jtfChassi.getText().isEmpty()) {
                throw new NumberFormatException("Chassi Invalido\n");
            }

            if (jtfPlaca.getText().isEmpty()) {
                throw new NumberFormatException("Placa Invalida\n");
            }

            if (jbgVeiculo.getSelection() == null) {
                throw new NumberFormatException("Escolha um Veículo!\n");
            }
            
            //dados motora
            Motorista motorista = new Motorista();
            
            motorista.setNome(jtfNome.getText());
            motorista.setCpf(jtfCpf.getText());
            motorista.setChassi(jtfChassi.getText());
            motorista.setCnh(jtfCnh.getText());
            motorista.setPlaca(jtfPlaca.getText());
            motorista.setVeiculo(jbgVeiculo.getSelection().getActionCommand());

            MotoristaServicos motoristaServicos= ServicosFactory.getMotoristaServicos();
            motoristaServicos.cadastrarMotorista(motorista);
            JOptionPane.showMessageDialog(rootPane, "Sucesso!\n Motorista cadastrado!");

        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro, dado inválido! " + numberFormatException.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);

        } catch (ArithmeticException arithmeticException) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro aritmético! " + arithmeticException.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);

        } catch (Exception exception) {
            JOptionPane.showMessageDialog(
                    this,
                    "Algum erro ocorreu! " + exception.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);

        } finally {
            System.out.println("passou em finally c:");
        }
    }//fecha cadastrar

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.ButtonGroup jbgVeiculo;
    private javax.swing.JLabel jlChassi;
    private javax.swing.JLabel jlChassiErro;
    private javax.swing.JLabel jlCnh;
    private javax.swing.JLabel jlCnhErro;
    private javax.swing.JLabel jlCpf;
    private javax.swing.JLabel jlCpfErro;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNomeErro;
    private javax.swing.JLabel jlPlaca;
    private javax.swing.JLabel jlPlacaErro;
    private javax.swing.JLabel jlVeiculo;
    private javax.swing.JLabel jlVeiculoErro;
    private javax.swing.JLayeredPane jlpAcoes;
    private javax.swing.JLayeredPane jlpDados;
    private javax.swing.JRadioButton jrbBicicleta;
    private javax.swing.JRadioButton jrbCarro;
    private javax.swing.JRadioButton jrbMoto;
    private javax.swing.JRadioButton jrbPatinete;
    private javax.swing.JTextField jtfChassi;
    private javax.swing.JTextField jtfCnh;
    private javax.swing.JTextField jtfCpf;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfPlaca;
    // End of variables declaration//GEN-END:variables
}
