/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.qi.visao;

import br.edu.qi.modelo.Distancia;
import java.awt.event.KeyEvent;

/**
 *
 * @author Diogenes Wilgner 
 * @since 27/06/2019 - 14:55
 * @version 1.0
 */
public class UICadDistancia extends javax.swing.JFrame {

    /**
     * Creates new form UICadDistancia
     */
    public UICadDistancia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlpCadDistancia = new javax.swing.JLayeredPane();
        jlpValorX1 = new javax.swing.JLabel();
        jlValorX2 = new javax.swing.JLabel();
        jlValorY1 = new javax.swing.JLabel();
        jlValorY2 = new javax.swing.JLabel();
        jtfValorX1 = new javax.swing.JTextField();
        jtfValorX2 = new javax.swing.JTextField();
        jtfValorY1 = new javax.swing.JTextField();
        jtfValorY2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaResposta = new javax.swing.JTextArea();
        jbCalcular = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlpCadDistancia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlpValorX1.setText("Valor X1");

        jlValorX2.setText("Valor X2");

        jlValorY1.setText("Valor Y1");

        jlValorY2.setText("Valor Y2");

        jtfValorX1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfValorX1KeyPressed(evt);
            }
        });

        jtfValorX2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfValorX2KeyPressed(evt);
            }
        });

        jtfValorY1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfValorY1KeyPressed(evt);
            }
        });

        jtfValorY2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfValorY2KeyPressed(evt);
            }
        });

        jtaResposta.setColumns(20);
        jtaResposta.setRows(5);
        jtaResposta.setFocusable(false);
        jScrollPane1.setViewportView(jtaResposta);

        jbCalcular.setText("Calcular");
        jbCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcularActionPerformed(evt);
            }
        });
        jbCalcular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCalcularKeyPressed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        jbLimpar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbLimparKeyPressed(evt);
            }
        });

        jlpCadDistancia.setLayer(jlpValorX1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadDistancia.setLayer(jlValorX2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadDistancia.setLayer(jlValorY1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadDistancia.setLayer(jlValorY2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadDistancia.setLayer(jtfValorX1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadDistancia.setLayer(jtfValorX2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadDistancia.setLayer(jtfValorY1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadDistancia.setLayer(jtfValorY2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadDistancia.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadDistancia.setLayer(jbCalcular, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadDistancia.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpCadDistanciaLayout = new javax.swing.GroupLayout(jlpCadDistancia);
        jlpCadDistancia.setLayout(jlpCadDistanciaLayout);
        jlpCadDistanciaLayout.setHorizontalGroup(
            jlpCadDistanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpCadDistanciaLayout.createSequentialGroup()
                .addGroup(jlpCadDistanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpCadDistanciaLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jlpCadDistanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlValorY2)
                            .addComponent(jlValorY1)
                            .addComponent(jlValorX2)
                            .addComponent(jlpValorX1))
                        .addGroup(jlpCadDistanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jlpCadDistanciaLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jtfValorY2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpCadDistanciaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jlpCadDistanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfValorY1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfValorX2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfValorX1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jlpCadDistanciaLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jlpCadDistanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jlpCadDistanciaLayout.setVerticalGroup(
            jlpCadDistanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpCadDistanciaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jlpCadDistanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jlpCadDistanciaLayout.createSequentialGroup()
                        .addGroup(jlpCadDistanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlpValorX1)
                            .addComponent(jtfValorX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jlpCadDistanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlValorX2)
                            .addComponent(jtfValorX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jlpCadDistanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlValorY1)
                            .addComponent(jtfValorY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jlpCadDistanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlValorY2)
                            .addComponent(jtfValorY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jbCalcular)
                        .addGap(36, 36, 36)
                        .addComponent(jbLimpar)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpCadDistancia)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpCadDistancia)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpar() {
        jtfValorX1.setText("");
        jtfValorX2.setText("");
        jtfValorY1.setText("");
        jtfValorY2.setText("");
        
    }//fecha limpar
    
    private void calcular() {
        Distancia distancia = new Distancia();
        
        distancia.setValorX1(Double.parseDouble(jtfValorX1.getText()));
        distancia.setValorY1(Double.parseDouble(jtfValorY1.getText()));
        distancia.setValorX2(Double.parseDouble(jtfValorX2.getText()));
        distancia.setValorY2(Double.parseDouble(jtfValorY2.getText()));
        
        jtaResposta.setText(distancia.toString());
    }
    
    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        // TODO add your handling code here:
        limpar();
        jtaResposta.setText("");
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcularActionPerformed
        // TODO add your handling code here:
        calcular();
    }//GEN-LAST:event_jbCalcularActionPerformed

    private void jtfValorX1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfValorX1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtfValorX2.grabFocus();
        }
    }//GEN-LAST:event_jtfValorX1KeyPressed

    private void jtfValorX2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfValorX2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtfValorY1.grabFocus();
        }
    }//GEN-LAST:event_jtfValorX2KeyPressed

    private void jtfValorY1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfValorY1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtfValorY2.grabFocus();
        }
    }//GEN-LAST:event_jtfValorY1KeyPressed

    private void jtfValorY2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfValorY2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jbCalcular.grabFocus();
        }
    }//GEN-LAST:event_jtfValorY2KeyPressed

    private void jbCalcularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCalcularKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            calcular();
            limpar();
            jbLimpar.grabFocus();
        }
    }//GEN-LAST:event_jbCalcularKeyPressed

    private void jbLimparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbLimparKeyPressed
        // TODO add your handling code here:
          if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            limpar();
            jtaResposta.setText("");
            jtfValorX1.grabFocus();
        }
    }//GEN-LAST:event_jbLimparKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UICadDistancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UICadDistancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UICadDistancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UICadDistancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UICadDistancia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCalcular;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlValorX2;
    private javax.swing.JLabel jlValorY1;
    private javax.swing.JLabel jlValorY2;
    private javax.swing.JLayeredPane jlpCadDistancia;
    private javax.swing.JLabel jlpValorX1;
    private javax.swing.JTextArea jtaResposta;
    private javax.swing.JTextField jtfValorX1;
    private javax.swing.JTextField jtfValorX2;
    private javax.swing.JTextField jtfValorY1;
    private javax.swing.JTextField jtfValorY2;
    // End of variables declaration//GEN-END:variables
}
