/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.qi.visao;

import javax.swing.UIManager;

/**
 *
 * @author Rudimiler P. Machado
 * @since 10/06/2019 - 16:43
 * @version 1.0 beta
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jAreaDeTrabalho = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCadastrar = new javax.swing.JMenu();
        jmiCadTorneio = new javax.swing.JMenuItem();
        jmiCadParticipante = new javax.swing.JMenuItem();
        jmManutencao = new javax.swing.JMenu();
        jmiManTorneio = new javax.swing.JMenuItem();
        jmiManParticipante = new javax.swing.JMenuItem();
        jmSair = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jAreaDeTrabalho.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jAreaDeTrabalhoLayout = new javax.swing.GroupLayout(jAreaDeTrabalho);
        jAreaDeTrabalho.setLayout(jAreaDeTrabalhoLayout);
        jAreaDeTrabalhoLayout.setHorizontalGroup(
            jAreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );
        jAreaDeTrabalhoLayout.setVerticalGroup(
            jAreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );

        jmCadastrar.setText("Cadastrar");

        jmiCadTorneio.setText("Torneio");
        jmiCadTorneio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadTorneioActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiCadTorneio);

        jmiCadParticipante.setText("Partcipante");
        jmiCadParticipante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadParticipanteActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiCadParticipante);

        jMenuBar1.add(jmCadastrar);

        jmManutencao.setText("Manutenção");
        jmManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmManutencaoActionPerformed(evt);
            }
        });

        jmiManTorneio.setText("torneio");
        jmManutencao.add(jmiManTorneio);

        jmiManParticipante.setText("participante");
        jmiManParticipante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManParticipanteActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiManParticipante);

        jMenuBar1.add(jmManutencao);

        jmSair.setText("Sair");
        jmSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAreaDeTrabalho)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAreaDeTrabalho)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirCadParticipante() {
        UICadParticipantes uICadParticipantes = new UICadParticipantes();
        jAreaDeTrabalho.add(uICadParticipantes);
        uICadParticipantes.setVisible(true);
    }//fecha abrirCadParticipante
    
    private void abrirCadTorneio() {
        UICadTorneio uICadTorneio = new UICadTorneio();
        jAreaDeTrabalho.add(uICadTorneio);
        uICadTorneio.setVisible(true);
    }//fecha abrirCadTorneio
    
    private void abrirManCadParticipante() {
        UICadManutencaoParticipante uICadManutencaoParticipante = new UICadManutencaoParticipante();
        jAreaDeTrabalho.add(uICadManutencaoParticipante);
        uICadManutencaoParticipante.setVisible(true);
    }//fecha abrirManParticipante
    
    private void abrirManCadTorneio() {
        UICadManutencaoTorneio uICadManutencaoTorneio = new UICadManutencaoTorneio();
        jAreaDeTrabalho.add(uICadManutencaoTorneio);
        uICadManutencaoTorneio.setVisible(true);
    }//fecha abrirManParticipante
    
    private void jmiCadParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadParticipanteActionPerformed
        abrirCadParticipante();
    }//GEN-LAST:event_jmiCadParticipanteActionPerformed

    private void jmiCadTorneioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadTorneioActionPerformed
        abrirCadTorneio();
    }//GEN-LAST:event_jmiCadTorneioActionPerformed

    private void jmManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmManutencaoActionPerformed
        abrirManCadParticipante();
    }//GEN-LAST:event_jmManutencaoActionPerformed

    private void jmiManParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManParticipanteActionPerformed
        abrirManCadTorneio();
    }//GEN-LAST:event_jmiManParticipanteActionPerformed

    private void jmSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jmSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
        com.jtattoo.plaf.acryl.AcrylLookAndFeel.setTheme("Black", "INSERT YOUR LICENSE KEY HERE", "my company");
        UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
        
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jAreaDeTrabalho;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jmCadastrar;
    private javax.swing.JMenu jmManutencao;
    private javax.swing.JMenu jmSair;
    private javax.swing.JMenuItem jmiCadParticipante;
    private javax.swing.JMenuItem jmiCadTorneio;
    private javax.swing.JMenuItem jmiManParticipante;
    private javax.swing.JMenuItem jmiManTorneio;
    // End of variables declaration//GEN-END:variables
}
