/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.qi.visao;

import br.edu.qi.modelo.TorneioVO;
import br.edu.qi.servicos.ParticipanteServicos;
import br.edu.qi.servicos.ServicosFactory;
import br.edu.qi.servicos.TorneioServicos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rudimiler P. Machado
 * @since 10/06/2019 - 16:18
 * @version 1.0 beta
 */
public class UICadManutencaoTorneio extends javax.swing.JInternalFrame {

    DefaultTableModel defaultTableModel
            = new DefaultTableModel(
                    new Object[][]{},
                    new Object[]{"Código", "Nome do Jogo", "Nome do Torneio", "Tipo de jogo", "times", "Participantes", "Rodadas"}
            );
    /**
     * Creates new form GUIManutencaoTorneio
     */
    public UICadManutencaoTorneio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableTorneio = new javax.swing.JTable();
        jtfCodigo = new javax.swing.JTextField();
        jtfTipodeJogo = new javax.swing.JTextField();
        jtfNomeDoJogo = new javax.swing.JTextField();
        jtfNomeDoTorneio = new javax.swing.JTextField();
        jtfPartcipantes = new javax.swing.JTextField();
        jtfTime = new javax.swing.JTextField();
        jtfRodadas = new javax.swing.JTextField();
        jlCodigo = new javax.swing.JLabel();
        jlNomedoJogo = new javax.swing.JLabel();
        jlNomeDoTorneio = new javax.swing.JLabel();
        jlTipodeJogo = new javax.swing.JLabel();
        jlRodadas = new javax.swing.JLabel();
        jlParticipantes = new javax.swing.JLabel();
        jlTime = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jbPreencher = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbLimpar1 = new javax.swing.JButton();
        jbLimpar2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Manutenção Torneio");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtableTorneio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", "", ""
            }
        ));
        jtableTorneio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableTorneioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableTorneio);

        jtfCodigo.setEnabled(false);

        jtfTipodeJogo.setEnabled(false);

        jtfNomeDoJogo.setEnabled(false);

        jtfNomeDoTorneio.setEnabled(false);

        jtfPartcipantes.setEnabled(false);

        jtfTime.setEnabled(false);

        jtfRodadas.setEnabled(false);

        jlCodigo.setText("Código");

        jlNomedoJogo.setText("Nome do Jogo");

        jlNomeDoTorneio.setText("Nome do Torneio");

        jlTipodeJogo.setText("Tipo de jogo");

        jlRodadas.setText("Rodadas");

        jlParticipantes.setText("Participantes");

        jlTime.setText("Time");

        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfTipodeJogo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfNomeDoJogo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfNomeDoTorneio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfPartcipantes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfTime, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfRodadas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlNomedoJogo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlNomeDoTorneio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlTipodeJogo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlRodadas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlParticipantes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlTime, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfRodadas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlCodigo))
                                .addGap(18, 18, 18)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlNomedoJogo)
                                    .addComponent(jtfNomeDoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfTipodeJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlTipodeJogo))
                                .addGap(18, 18, 18)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfTime, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlTime)))
                            .addComponent(jlRodadas))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfPartcipantes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNomeDoTorneio, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNomeDoTorneio)
                            .addComponent(jlParticipantes))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCodigo)
                    .addComponent(jlNomedoJogo)
                    .addComponent(jlNomeDoTorneio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNomeDoTorneio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNomeDoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTipodeJogo)
                    .addComponent(jlParticipantes)
                    .addComponent(jlTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTipodeJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPartcipantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlRodadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfRodadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbPreencher.setText("Preencher");
        jbPreencher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPreencherActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbLimpar1.setText("Alterar");
        jbLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpar1ActionPerformed(evt);
            }
        });

        jbLimpar2.setText("Deletar");
        jbLimpar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpar2ActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jbPreencher, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbLimpar1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbLimpar2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jbPreencher, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbLimpar2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbLimpar1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbPreencher, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimpar2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimpar1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1)
                    .addComponent(jLayeredPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preencher() {
        try {
            
            TorneioServicos torneioServicos = ServicosFactory.getTorneioServicos();
            ArrayList<TorneioVO> torneio = torneioServicos.buscarTorneio();
            
            for (int i = 0; i < torneio.size(); i++) {
                defaultTableModel.addRow(new String[]{
                    String.valueOf(torneio.get(i).getIdtorneio()),
                    torneio.get(i).getNomeDoJogo(),
                    torneio.get(i).getNomeDoTorneio(),
                    torneio.get(i).getTipoDeJogo(),
                    String.valueOf(torneio.get(i).getTimes()),
                    String.valueOf(torneio.get(i).getRodadas()),
                    String.valueOf(torneio.get(i).getParticipantes()),
                });
            }//fecha for
                jtableTorneio.setModel(defaultTableModel);
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(rootPane,
                        "Erro!" + exception.getMessage());
        }//fecha try
    }//fecha preencher
    
    private void deletar() {
        try {
            int linha = jtableTorneio.getSelectedRow();
            if (linha == -1) {
                JOptionPane.showMessageDialog(this,
                        "Selecione uma linha para excluir!");
                return;
            }//fecha if
            TorneioServicos torneioServicos = ServicosFactory.getTorneioServicos();
            String id
                    = jtableTorneio.getValueAt(linha, 0).toString();
            torneioServicos.deletarTorneio(Long.parseLong(id));

            JOptionPane.showMessageDialog(this,
                    "Torneio excluido com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro! " + e.getMessage());
        }//catch
    }//deletar
    
    private void alterar() {
        
        int linha = jtableTorneio.getSelectedRow();
        String id = jtableTorneio.getValueAt(linha, 0).toString();
        String nomeDoJogo = jtableTorneio.getValueAt(linha, 1).toString();
        String nomeDoTorneio = jtableTorneio.getValueAt(linha, 2).toString();
        String tipoDejogo = jtableTorneio.getValueAt(linha, 3).toString();
        String time = jtableTorneio.getValueAt(linha, 4).toString();
        String participante = jtableTorneio.getValueAt(linha, 5).toString();
        String rodadas = jtableTorneio.getValueAt(linha, 6).toString();
        
        jtfCodigo.setText(id);
        jtfNomeDoJogo.setText(nomeDoJogo);
        jtfNomeDoTorneio.setText(nomeDoTorneio);
        jtfPartcipantes.setText(participante);
        jtfRodadas.setText(rodadas);
        jtfTipodeJogo.setText(tipoDejogo);
        jtfTime.setText(time);

        
    }//fecha alterar
    
    private void confirmarAlteracao() {
        try {
            TorneioVO torneioVO = new TorneioVO();
            torneioVO.setNomeDoJogo(jtfNomeDoJogo.getText());
            torneioVO.setNomeDoTorneio(jtfNomeDoTorneio.getText());
            torneioVO.setParticipantes(Integer.parseInt(jtfPartcipantes.getText()));
            torneioVO.setRodadas(Integer.parseInt(jtfPartcipantes.getText()));
            torneioVO.setTipoDeJogo(jtfNomeDoTorneio.getText());
            torneioVO.setTimes(Integer.parseInt(jtfTime.getText()));
            
            TorneioServicos torneioServicos = ServicosFactory.getTorneioServicos();
            torneioServicos.alterarTorneio(torneioVO);

            JOptionPane.showMessageDialog(
                    rootPane,
                    "Participante alterado com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro! " + e.getMessage());
        }//catch
    }//fecha confirmarAlteração

    private void limpar() {
    }//fecha limpar


    private void jbPreencherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPreencherActionPerformed
        limpar();
        preencher();
    }//GEN-LAST:event_jbPreencherActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpar1ActionPerformed
        confirmarAlteracao();
    }//GEN-LAST:event_jbLimpar1ActionPerformed

    private void jbLimpar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpar2ActionPerformed
        deletar();
        limpar();
        preencher();
    }//GEN-LAST:event_jbLimpar2ActionPerformed

    private void jtableTorneioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableTorneioMouseClicked
        alterar();
    }//GEN-LAST:event_jtableTorneioMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbLimpar1;
    private javax.swing.JButton jbLimpar2;
    private javax.swing.JButton jbPreencher;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlNomeDoTorneio;
    private javax.swing.JLabel jlNomedoJogo;
    private javax.swing.JLabel jlParticipantes;
    private javax.swing.JLabel jlRodadas;
    private javax.swing.JLabel jlTime;
    private javax.swing.JLabel jlTipodeJogo;
    private javax.swing.JTable jtableTorneio;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfNomeDoJogo;
    private javax.swing.JTextField jtfNomeDoTorneio;
    private javax.swing.JTextField jtfPartcipantes;
    private javax.swing.JTextField jtfRodadas;
    private javax.swing.JTextField jtfTime;
    private javax.swing.JTextField jtfTipodeJogo;
    // End of variables declaration//GEN-END:variables
}
