/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.qi.visao;

import br.edu.qi.modelo.TorneioVO;
import javax.swing.JOptionPane;

/**
 *
 * @author Rudimiler P. Machado
 * @since 06/06/2019 - 16:30
 * @version 1.0 beta
 */
public class UICadTorneio extends javax.swing.JInternalFrame {

    /**
     * Creates new form UICadTorneio
     */
    public UICadTorneio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlpDados = new javax.swing.JLayeredPane();
        jlNomeDoTorneio = new javax.swing.JLabel();
        jlNomeDoJogo = new javax.swing.JLabel();
        jlTipoDeJogo = new javax.swing.JLabel();
        jlTime = new javax.swing.JLabel();
        jlParticipantes = new javax.swing.JLabel();
        jlRodadas = new javax.swing.JLabel();
        jtfNomeDoTorneio = new javax.swing.JTextField();
        jtfNomeDoJogo = new javax.swing.JTextField();
        jtfTipoDeJogo = new javax.swing.JTextField();
        jtfTime = new javax.swing.JTextField();
        jtfParticipantes = new javax.swing.JTextField();
        jtfRodadas = new javax.swing.JTextField();
        jlpAcoes = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jlpDados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNomeDoTorneio.setText("Nome do Torneio:");

        jlNomeDoJogo.setText("Nome do Jogo:");

        jlTipoDeJogo.setText("Tipo de Jogo:");

        jlTime.setText("Time:");

        jlParticipantes.setText("Participantes:");

        jlRodadas.setText("Rodadas:");

        jlpDados.setLayer(jlNomeDoTorneio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlNomeDoJogo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlTipoDeJogo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlTime, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlParticipantes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlRodadas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtfNomeDoTorneio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtfNomeDoJogo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtfTipoDeJogo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtfTime, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtfParticipantes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtfRodadas, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpDadosLayout = new javax.swing.GroupLayout(jlpDados);
        jlpDados.setLayout(jlpDadosLayout);
        jlpDadosLayout.setHorizontalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlRodadas)
                    .addComponent(jlParticipantes)
                    .addComponent(jlTime)
                    .addComponent(jlTipoDeJogo)
                    .addComponent(jlNomeDoJogo)
                    .addComponent(jlNomeDoTorneio))
                .addGap(63, 63, 63)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfNomeDoTorneio)
                    .addComponent(jtfNomeDoJogo)
                    .addComponent(jtfTipoDeJogo)
                    .addComponent(jtfTime)
                    .addComponent(jtfParticipantes)
                    .addComponent(jtfRodadas, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlpDadosLayout.setVerticalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomeDoTorneio)
                    .addComponent(jtfNomeDoTorneio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomeDoJogo)
                    .addComponent(jtfNomeDoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTipoDeJogo)
                    .addComponent(jtfTipoDeJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTime)
                    .addComponent(jtfTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlParticipantes)
                    .addComponent(jtfParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlRodadas)
                    .addComponent(jtfRodadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jlpAcoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jlpAcoes.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAcoesLayout = new javax.swing.GroupLayout(jlpAcoes);
        jlpAcoes.setLayout(jlpAcoesLayout);
        jlpAcoesLayout.setHorizontalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jlpAcoesLayout.setVerticalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlpAcoes)
                    .addComponent(jlpDados))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlpAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar() {
        
        TorneioVO torneio = new TorneioVO();
        try {
            if(jtfNomeDoJogo.getText().isEmpty()) {
                throw new NumberFormatException("Nome inválido!");
            }//fecha if(Nome do jogo)
            
            if(jtfNomeDoTorneio.getText().isEmpty()) {
                throw new NumberFormatException();
            }//fecha if(Nome do torneio)
            
            if(jtfTime.getText().isEmpty()) {
                throw new NumberFormatException();
            }//fecha if(Time)
            
            if(jtfTipoDeJogo.getText().isEmpty()) {
                throw new NumberFormatException();
            }//fecha if(Tipo de jogo)
            
            if(jtfParticipantes.getText().isEmpty()) {
                throw new NumberFormatException();
            }//fecha if(Participante)
            
            if(jtfRodadas.getText().isEmpty()) {
                throw new NumberFormatException();
            }//fecha if(Rodadas)
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(rootPane,
                    "Erro!" + exception.getMessage());
        }//fecha catch
        
        
        torneio.setNomeDoJogo(jtfNomeDoJogo.getText());
        torneio.setNomeDoTorneio(jtfNomeDoTorneio.getText());
        torneio.setParticipantes(Integer.parseInt(jtfParticipantes.getText()));
        torneio.setRodadas(Integer.parseInt(jtfRodadas.getText()));
        torneio.setTimes(Integer.parseInt(jtfTime.getText()));
        torneio.setTipoDeJogo(jtfTipoDeJogo.getText());
    }//fecha cadastrar
    
    private void limpar() {
        
        jtfNomeDoJogo.setText("");
        jtfNomeDoTorneio.setText("");
        jtfParticipantes.setText("");
        jtfRodadas.setText("");
        jtfTime.setText("");
        jtfTipoDeJogo.setText("");
    }//fecha limpar
    
    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();
        limpar();
        jtfNomeDoTorneio.grabFocus();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
        jtfNomeDoTorneio.grabFocus();
    }//GEN-LAST:event_jbLimparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlNomeDoJogo;
    private javax.swing.JLabel jlNomeDoTorneio;
    private javax.swing.JLabel jlParticipantes;
    private javax.swing.JLabel jlRodadas;
    private javax.swing.JLabel jlTime;
    private javax.swing.JLabel jlTipoDeJogo;
    private javax.swing.JLayeredPane jlpAcoes;
    private javax.swing.JLayeredPane jlpDados;
    private javax.swing.JTextField jtfNomeDoJogo;
    private javax.swing.JTextField jtfNomeDoTorneio;
    private javax.swing.JTextField jtfParticipantes;
    private javax.swing.JTextField jtfRodadas;
    private javax.swing.JTextField jtfTime;
    private javax.swing.JTextField jtfTipoDeJogo;
    // End of variables declaration//GEN-END:variables
}

